version: '3.4'

services:
  db:
    image: postgres:16.2
    env_file:
      - .env

  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/opt/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  aweb:
    build: .
    env_file:
      - .env
    volumes:
      - .:/opt/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: uvicorn project.asgi:application --reload --host 0.0.0.0 --port 8001
