version: '3.4'

services:
  db:
    image: postgres:16.2
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: ./prod/Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - db
    command: bash ./prod/scripts/run-sync.sh

  aweb:
    build:
      context: .
      dockerfile: ./prod/Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - db
    command: bash ./prod/scripts/run-async.sh

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - web
      - aweb

volumes:
  static_volume:
  shm:
